# Test your FastAPI endpoints

GET http://127.0.0.1:8001/api/jobs/104/?keywords=python
Accept: application/json

###

GET http://127.0.0.1:8001/api/jobs/1111/?keywords=python
Accept: application/json

###
